image:
  repository: kkeducation123456/java-web-app
  pullPolicy: IfNotPresent
  tag: "1.0.1"

service:
  type: NodePort
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 75
